version: '3.3'

services:
  geoportal:
    image: geoportal
    ports: 
# keep it off 8080 on local dev
      - "8082:8080"
    hostname: geoportal
    environment:
      - es_cluster=es-geoportal
      - es_node=elasticsearch
      - gpt_authentication=authentication-simple.xml
    volumes:
      - gptharvester:/root
      - gptmetadata:/opt/tomcat/webapps/metadata
    networks:
      - sp-net
      - traefik-public
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.50'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
          - traefik.enable=true
          - traefik.docker.network=traefik-public
          - traefik.constraint-label=traefik-public
          - traefik.http.routers.geoportal.rule=Host(`${GEOPORTAL_DOMAIN?Variable not set}`)
          - traefik.http.routers.geoportal.entrypoints=http
          - traefik.http.middlewares.geoportal.redirectscheme.scheme=https
          - traefik.http.middlewares.geoportal.redirectscheme.permanent=true
          - traefik.http.routers.geoportal-secured.rule=Host(`${GEOPORTAL_DOMAIN?Variable not set}`)
          - traefik.http.routers.geoportal-secured.entrypoints=https
          - traefik.http.routers.geoportal-secured.tls.certresolver=le
          - traefik.http.services.geoportal-secured.loadbalancer.server.port=8080

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch1
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - discovery.type=single-node
      - cluster.name=es-geoportal
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
    networks:
      - sp-net
    deploy:
      placement:
        constraints: [node.role == manager]
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 512M
#        reservations:
#          cpus: '0.25'
#          memory: 512M

#  elasticsearch2:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
#    container_name: elasticsearch2
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - xpack.security.enabled=false
#      - xpack.ml.enabled=false
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata2:/usr/share/elasticsearch/data
#    networks:
#      - default
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 512M
#        reservations:
#          cpus: '0.25'
#          memory: 256M

# ########pain point removed
# requires creation of an  geoportal network.
# docker network geoportal create
###########
networks:
  sp-net:
    external: true
  traefik-public:
    external: true

volumes:
  esdata1:
    driver: local
  gptharvester:
    driver: local
  gptmetadata:
    driver: local